# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d91ac22fa08958cfd66b0a5456697ba2c0aa2ce6c53a5cb4d351c0a36175700674a9990b4659e79510ebad5050a1f731996dcaa7c99e6607287fc0fc9df34b9a

test:
  secret_key_base: 393ad37c7bdc85febc7ee2361bda5ba5092a8dad0c5e40a4de4ed843c614d88ab4751d91a35da11da1381d140557eff46de685d753240a115b3e42cdce68dc7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
